tester:
	# copiando código do estudante para soma.sci
	chmod +x lgcor.sh
	cp __USERCODE__ ha_query.circ

run:
	# executando testador
	./lgcor.sh -t main.circ -s ha_solution.circ -q ha_query.circ -r RAM.txt
