
tester:	tester.cpp
	# copiando código do estudante para soma.h
	cp __USERCODE__ soma.h
	# compilando testador (com o código do estudante)
	g++ tester.cpp -o tester

run:	tester
	# executando testador
	./tester
